### ISSUE TITLE
Disabling "changeSkybox" non functional

### ISSUE THREAD

**Issue by MrNiceUK** [net-lisias-ksp/DistantObject#14]
As per title, with latest KSP 1.12.2 and DOE 2.1.1.6, disabling sky box darkening either via `Settings.cfg` or the in game UI has no effect...

**Comment by Lisias** [comment]
That's a major flaw. It will be fixed in the next release. Thanks for the head's up, @MrNiceUK .

**Comment by Lisias** [comment]
I confirm the problem, just reproduced it. Damn.

**Comment by Lisias** [comment]
Fixed on commit https://github.com/net-lisias-ksp/DistantObject/commit/e116eb8656e99e26b7452575a6455a9213d4cbc1 . 

This will be issued Soon™, probably on Thursday or Friday. Thanks for the heads up, @MrNiceUK !
