### ISSUE TITLE
Increase of max distance to render (e.g for RSS)

### ISSUE THREAD

**Issue by MrFibunacci** [net-lisias-ksp/DistantObject#21]
When playing in the real-scale solar system it is very rare that objects get within 750km of one another, therefore barely any other objects except the planets get displayed. 

So I thought I could just check the config file and increase the max distance to render (i tried to increase it by a factor of about 10x) but this change had no real effect because in the game the slider won't let me set the distance to that new max value because the slider 'breaks'.

![broken_slider](https://user-images.githubusercontent.com/12794953/179319837-5c9202fd-7cd2-4f1d-bcc4-f945228afcd7.png)

Is there a way to implement this? Maybe with a special config for RSS and a quick fix in the slider code?

**Comment by MrFibunacci** [comment]
I think this can be done here https://github.com/net-lisias-ksp/DistantObject/blob/master/Source/DistantObject/SettingsGui.cs#L299 but I am not sure.

**Comment by Lisias** [comment]
Hi @MrFibunacci 

Thanks for the suggestion.

You are right, that is the place for such change. 

However, before doing it on the mainstream, I think it would be a good idea to release it as a beta to see if by expanding this thing too much KSP would not break - sometimes, these arbitrary limits on the code were get by empirical testings: we don't really know why things start to break at some level, we only knows that things start to break at some level.

Let's try a stunt: I will allow this limit to be configurable by a MM patch - so people can take their chances to see what they can get. I will keep the default limit at 750.000KM, but any MM patch will be able to expand it. Who knows we would not get lucky on this and KSP will behave nicely? :)

I'm shoving this to be published on the 2.2.0.0 release, to be worked soon - right now I'm focused on bug fixes.

**Comment by Lisias** [comment]
Wait… I worked on this one already…

On commit https://github.com/net-lisias-ksp/DistantObject/commit/a7e53d48a2f686fb17e3e9a021535ecdf297fe48 I allowed the maxium distance possible to be patched by MM on the file

`<KSP_ROOT>/GameData/DistantObject/Setting.cfg`.

See https://github.com/net-lisias-ksp/DistantObject/blob/b7c27d2686850d9a0a8fa9a549bd1efab6d5fa86/Source/DistantObject/Settings.cs#L74

Why this is still opened?

**Comment by Lisias** [comment]
And it was released on 2.1.1.12 :/

Well, closing it so.
