### ISSUE TITLE
Are there supposed to be 3 different settings files?

### ISSUE THREAD

**Issue by Tuupertunut** [net-lisias-ksp/DistantObject#40]
There are currently 3 different settings files for this mod:

- kspdir/PluginData/DistantObject/Settings.cfg
- kspdir/GameData/DistantObject/Settings.cfg
- kspdir/GameData/DistantObject/PluginData/Settings.cfg

I can see a reason for a default config and a user config but what about the third one? Are all of these 3 supposed to be there?

**Comment by Lisias** [comment]
Whoopsie… I let this one pass trough…

Well, yes. 

The `kspdir/GameData/DistantObject/Settings.cfg` is the global configuration file, where settings about the setup itself is stored. User has not access to these values, they are meant to be customised by MM patches.

The `kspdir/GameData/DistantObject/PluginData/Settings.cfg` is the template with default values for user's configurations. Everytime you click "Default" or the user's configuration file is missing, this file is loaded instead.

The `kspdir/PluginData/DistantObject/Settings.cfg` is the user's configuration file. To tell you the true, it's on the wrong place - it should be placed inside he user's save, so they can customise DOE on a savegame basis - not to mention that the settings will be sync'ed with cloud services.

In a way or another, https://github.com/net-lisias-ksp/DistantObject/issues/41 . 

Cheers!

**Comment by Lisias** [comment]
Closing this as concluded, since the question was answered. Any further questioning or suggestions should be directed to https://github.com/net-lisias-ksp/DistantObject/issues/41 .
