### ISSUE TITLE
Windows of another mod (RP1) affected by Distant Object settings window

### ISSUE THREAD

**Issue by Test-Account-New** [net-lisias-ksp/DistantObject#45]
After opening the Distant Object settings window in the space center, the text in all windows of another mod (RP1) becomes right-aligned instead of left-aligned. The issue persists until KSP is restarted.

![screenshot35](https://github.com/user-attachments/assets/a64dcf5e-72bb-4503-87a9-0b41716d8763)

![image](https://github.com/user-attachments/assets/f7d977a0-5dcb-4a2b-aea3-94bf2090e34b)

**Comment by Lisias** [comment]
Yep, I confirm the problem. It was reported on Forum too, and I ended up fixing it before reading the issue tracker!

It was fixed on commit https://github.com/net-lisias-ksp/DistantObject/commit/8e8240c08c4653b2f40420ac4ba5fe371d566391 and it's already released on 2.2.0.2 . 

Thanks for the report!

Cheers!
