### ISSUE TITLE
Settings GUI Fails to load with RP-1

### ISSUE THREAD

**Issue by njd80** [net-lisias-ksp/DistantObject#47]
Flight scene  - no settings GUI & multiple instances of log errors

	Line 362795: [LOG 20:48:48.782] [AddonLoader]: Instantiating addon 'SettingsGuiOnGameScenes' from assembly 'DistantObject'
	Line 362806: 	DistantObject.Globals.get_CONFIG_PATHNAME () (at <0af4b36e98eb46beaaf864ed90a99393>:0)
	Line 362807: 	DistantObject.Settings.LoadSettings () (at <0af4b36e98eb46beaaf864ed90a99393>:0)
	Line 362808: 	DistantObject.Settings.Load () (at <0af4b36e98eb46beaaf864ed90a99393>:0)
	Line 362809: 	DistantObject.SettingsGui.ReadSettings () (at <0af4b36e98eb46beaaf864ed90a99393>:0)
	Line 362810: 	DistantObject.SettingsGui.Awake () (at <0af4b36e98eb46beaaf864ed90a99393>:0)
	Line 362811: 	DistantObject.SettingsGuiOnGameScenes.Awake () (at <0af4b36e98eb46beaaf864ed90a99393>:0)****

**Comment by Lisias** [comment]
Not only on RP-1, it was a really small mishap but with huge consequences on handling `Regex` and Windows Pathnames.

It was reported on Forum, and I fixed it on commit https://github.com/KSP-ModularManagement/KSPe/commit/69840edef038d0b5b9a0f8d309230ed1fb22a9ee (on KSPe project) before checking your issue.

It's fixed already and available on 2.2.0.2.

Thanks for reporting it!
