### ISSUE TITLE
A large square on the skybox

### ISSUE THREAD

**Issue by wingstrong** [net-lisias-ksp/DistantObject#51]
![3453452](https://github.com/user-attachments/assets/53e8dbf7-e290-4275-8bc2-4858b0979d39)

EnvironmentalVisualEnhancements
Milkyway-Skybox-SpaceEngine
Parallax
PlanetShine
Scatterer

**Comment by Lisias** [comment]
Wow, just found this by accident.

For anyone reading this in the future, the SkyBox textures used by the user's rig are screwed. The DDS itself my be at fault on the disk, or perhaps a SkyBox replacer borked in the boot.

In a way or another, DistantObject doesn't touches the SkyBox except by it's visibility - so it uses whatever it founds in the GameData, never doing anything that could completely screw up only 1 of the SkyBox's textures (there're 6, the Sky is a cube! :) )

**Comment by Lisias** [comment]
Hummm... "invalid" is wrong. The problem existed, it's only unrelated to DOE.
